# Generated by Django 3.2.7 on 2021-09-03 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hp', models.PositiveIntegerField()),
                ('attack', models.PositiveIntegerField()),
                ('defense', models.PositiveIntegerField()),
                ('special_attack', models.PositiveIntegerField()),
                ('special_defense', models.PositiveIntegerField()),
                ('speed', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, unique=True)),
                ('height', models.PositiveIntegerField()),
                ('weight', models.PositiveIntegerField()),
                ('base_stats', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemons.basestats')),
                ('evolves_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pokemons.pokemon')),
            ],
        ),
        migrations.CreateModel(
            name='EvolutionChain',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemons.pokemon')),
            ],
        ),
    ]
