# Generated by Django 3.2.7 on 2021-09-03 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='base_stats',
            field=models.JSONField(),
        ),
    ]
